import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import './assets/css/app.css'
import './assets/css/themain.css'
import './assets/css/padmin.css'
import './assets/css/Log-Re.css'
import './assets/css/AUPage.css'
import './assets/css/addadmin.css'
import './assets/css/setting.css'
import './assets/css/edit.css'
import './assets/css/food.css'
import './assets/css/firstpage.css'
import './assets/css/showcart.css'
createApp(App).use(router).mount('#app')
